# --------------
# -- Settings --
# --------------

# Ignore this. This is only if you're hosting this in a sub-folder.
# If you're using GitHub pages, they automatically override this with the right value.
baseurl: "/ROBOHackIT2022"

# If you're using GitHub pages without a custom domain, this is "https://[github username].github.io"
# If you're using GitHub pages with a custom domain, this is "http://[your domain]" (or https if you're using SSL)
url: "https://robocompsci.github.io"

# The ability to use custom themes.
style:
  theme: "original"

# This will help you track who's visiting your website.
tracking:
  google_analytics: "UA-43729070-14"

# Let people connect & engage with you through social media.
social:
  twitter_handle: "ROBO_CS"

# This is Search Engine Optimization. It'll help your website look better on search.
seo:
  title:       "ROBOHackIT | October 8-9 2022"
  description: "Building innovative solutions that will empower future students and bridge gaps in education."
  image:       "https://prime.mlh.io/img/logos/mlh-prime-color.svg"

# Event information.
event:
  name:        "ROBOHackIT"
  description: "Robinson Secondary invites hackers to ROBOHackIT 2022! Let's build innovative solutions that will empower students and bridge gaps in education together."
  date:        "October 2022"
  location:    "Robinson CS Club's EdTech Hackathon"

  trust_badge:
    year:   "2022"  # season year
    color:  "yellow" # "white", "black", "gray", "red", "blue" or "yellow"

  hero:
    links:
      - text: "Pre-Register"
        href: "https://forms.gle/LCPek6GaLpmaNiaT8"
      - text: "Apply w/ MyMLH"
        my_mlh:
          client_id:    "0e2f9fc2921d3ad3e12ae900af630d09382e1b3dc1b5b50de2b01b70ad64dbee"
          redirect_uri: "https://robocompsci.github.io/ROBOHackIT2022/success.html"
      - text: "Sponsor 2022"
        href: "mailto:robocompsci@gmail.com" # Needs to direct to internal page

  about:
    description: >
      ROBOHackIT is a 24 hour online hackathon hosted by James W. Robinson Secondary School in Fairfax, Virginia.
      Strap in for an exciting event with guest speakers, workshops, minigames, and prizes! 
      GOAL: Design or code innovative tech solutions for learners all around the world.

  # Info Sections
  acts:
    sections:
      - image: "images/cowork.svg"
        title: "TEAM UP!"
        description: >
          Come together in teams of up to 4 to spin up a programming solution in under 24 hours!
      - image: "images/solowork.svg"
        title: "BUILD"
        description: >
          Develop or design innovative projects to advance educational technology!
      - image: "images/proudcoder.svg"
        title: "LEARN"
        description: >
          Practice design and development skills and learn from a slew of mentors.

  sponsors:
    sections:
      - image: "images/icondev.svg"
        title: "Sponsor 1"
        description: >
          Come together in teams of up to 4 to spin up a programming solution in under 24 hours!
      - image: "images/opensource.svg"
        title: "Sponsor 2"
        description: >
          Develop or design innovative projects to advance educational technology!
      - image: "images/remotemeeting.svg"
        title: "Sponsor 3"
        description: >
          Practice design and development skills and learn from a slew of mentors.

  speakers:
    sections:
      - image: "images/robohackitcircle.svg"
        title: "Coming soon!"
        subtitle: "Mentor @ ROBOHackIT 2022"
        description: >
          This could be you! ROBOHackIT needs passionate mentors and speakers to encourage and inspire hackers to innovate!
      - image: "images/robohackitcircle.svg"
        title: "Coming soon!"
        subtitle: "Speaker @ ROBOHackIT 2022"
        description: >
          If you're interested in being a part of ROBOHackIT 2022, contact us now to get started!

  judges:
    sections:
      - image: "images/robohackitcircle.svg"
        title: "This could be you!"
        description: >
          If you're interested in judging projects for ROBOHackIT, contact us to get started!

  team:
    sections:
      - image: "images/karsten.svg"
        title: "Karsten Assoua"
        description: >
          Co-Founder
      - image: "images/ethan.svg"
        title: "Ethan Coon"
        description: >
          Co-Founder
      - image: "images/cherry.svg"
        title: "Cherry Lin"
        description: >
          Operations Lead
      # - image: "images/bryan.svg"
      #   title: "Bryan Tomer"
      #   description: >
      #     Outreach Lead

  # Frequently asked questions.
  faq:
    - question: "What is a hackathon?"
      answer: >
        A hackathon is an invention marathon. Students come together to build and design cool
        software over 24-48 hours. It's [super beginner friendly](https://medium.com/@tfogo/hackathons-are-for-beginners-77a9c9c0e000#.cj21niskl).
    - question: "How much does it cost?"
      answer: >
        Nothing. ROBOHacks is free for everyone!
    - question: "Do I need to be a student to attend?"
      answer: >
        Yes. Only students who are currently enrolled at a college/university or
        have graduated within the past 12 months are eligible to attend.
    - question: "Where is the hackathon?"
      answer: >
        ROBOHacks will be entirely digital this year, facilitated by Discord and Devpost.
    - question: "What is Major League Hacking?"
      answer: >
        Major League Hacking is [the official student hackathon league](https://mlh.io) in North America & Europe.
        MLH works with over 200 Member Events and empowers over 70,000 students every year.
    - question: "Is there a code of conduct?"
      answer: >
        Yes there is, and it's strictly enforced. You can [find it here](https://static.mlh.io/docs/mlh-code-of-conduct.pdf).

  # This is the message you'll receive once you've registered.
  register:
    message: >
      Thanks for registering!
    subtitle: "You'll receive more information closer to the hackathon."

# ----------------------------------------------------
# -- Ignore this unless you know what you're doing. --
# ----------------------------------------------------

markdown: kramdown
exclude:
 - node_modules
 - gulpfile.js
 - Gemfile
 - Gemfile.lock
 - package.json
 - README.md
 - CNAME
