# --------------
# -- Settings --
# --------------

# Ignore this. This is only if you're hosting this in a sub-folder.
# If you're using GitHub pages, they automatically override this with the right value.
baseurl: "/mlh-hackathon-boilerplate"

# If you're using GitHub pages without a custom domain, this is "https://[github username].github.io"
# If you're using GitHub pages with a custom domain, this is "http://[your domain]" (or https if you're using SSL)
url: "https://robocompsci.github.io"

# The ability to use custom themes.
style:
  theme: "original"

# This will help you track who's visiting your website.
tracking:
  google_analytics: "UA-43729070-14"

# Let people connect & engage with you through social media.
social:
  twitter_handle: "ROBO_CS"

# This is Search Engine Optimization. It'll help your website look better on search.
seo:
  title:       "ROBOHacks | October 2022"
  description: "Building innovative solutions that will empower future students and bridge gaps in education."
  image:       "https://prime.mlh.io/img/logos/mlh-prime-color.svg"

# Event information.
event:
  name:        "ROBOHacks"
  description: "Robinson Secondary invites hackers to build innovative solutions that will empower students and bridge gaps in education @ ROBOHacks!"
  date:        "October 2022"
  location:    "Robinson CS Club's EdTech Hackathon"

  trust_badge:
    year:   "2022"  # season year
    color:  "yellow" # "white", "black", "gray", "red", "blue" or "yellow"

  hero:
    links:
      - text: "Apply Now"
        my_mlh:
          client_id:    "0e2f9fc2921d3ad3e12ae900af630d09382e1b3dc1b5b50de2b01b70ad64dbee"
          redirect_uri: "https://robocompsci.github.io/mlh-hackathon-boilerplate/success.html"
      - text: "Sponsor 2022"
        href: "mailto:robocompsci@gmail.com" # Needs to direct to internal page

  about:
    description: >
      ROBOHacks is a 24 hour online hackathon hosted by James W. Robinson Secondary School in Fairfax, Virginia.
      Strap in for an exciting event with guest speakers, workshops, minigames, and prizes! 
      GOAL: Design or code innovative tech solution for learners all around the world.

  # Info Sections
  info:
    sections:
      - image: "images/image1.png"
        title: "LEARN."
        description: >
          We can write something nice with a graphic (as above) to make the event more appealing.
      - image: "images/image2.png"
        title: "BUILD."
        description: >
          We can write something nice with a graphic (as above) to make the event more appealing.
      - image: "images/image3.png"
        title: "SHARE."
        description: >
          We can write something nice with a graphic (as above) to make the event more appealing.

  # Frequently asked questions.
  faq:
    - question: "What is a hackathon?"
      answer: >
        A hackathon is an invention marathon. Students come together to build cool
        software & hardware hacks over 24-48 hours. It's [very beginner friendly](https://medium.com/@tfogo/hackathons-are-for-beginners-77a9c9c0e000#.cj21niskl).
    - question: "How much does it cost?"
      answer: >
        Nothing. ROBOHacks is free for everyone.
    - question: "Do I need to be a student to attend?"
      answer: >
        Yes. Only students who are currently enrolled at a college/university or
        have graduated within the past 12 months are eligible to attend.
    - question: "Where is the hackathon?"
      answer: >
        The hackathon will be entirely digital this year.
    - question: "What is Major League Hacking?"
      answer: >
        Major League Hacking is [the official student hackathon league](https://mlh.io) in North America & Europe.
        We work with over 200 Member Events and empower over 70,000 students every year.
    - question: "Is there a code of conduct?"
      answer: >
        Yes there is, and it's strictly enforced. You can [find it here](https://static.mlh.io/docs/mlh-code-of-conduct.pdf).

  # This is the message you'll receive once you've registered.
  register:
    message: >
      Thanks for registering!
    subtitle: "You'll receive more information closer to the hackathon."

# ----------------------------------------------------
# -- Ignore this unless you know what you're doing. --
# ----------------------------------------------------

markdown: kramdown
exclude:
 - node_modules
 - gulpfile.js
 - Gemfile
 - Gemfile.lock
 - package.json
 - README.md
 - CNAME
